# Generated by Django 3.2.13 on 2022-08-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_favouriteditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouritedItem',
        ),
    ]
